baseURL: "https://thedatafixer.xyz/"
languageCode: en-us
title: The Data Fixer 
theme: PaperMod
paginate: 10 

enableRobotsTXT: true
enableEmoji: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  author: Omar Valdez
  description: "#dataengineering #datainfra #datascience #bigdata"
  keywords: [blog, portfolio, theDataFixer, papermod]

  label:
    icon: "/favicon/favicon.ico"
    iconHeight: 35

  profileMode:
    enabled: true
    title: The Data Fixer
    subtitle: Desbloqueando el Potencial de los Datos
    imageURL: terrariaMaker.png
    imageWidth: 130
    imageHeight: 120
    imageTitle: https://demize.gg/TerrariaMaker/
    buttons:
      - name: About Me
        url: aboutme
      - name: Search
        url: search
      - name: Posts
        url: posts
 
  socialIcons:
    - name: "github"
      url: "https://github.com/theDataFixer" 
    - name: "youtube"
      url: "https://youtube.com/@theDataFixer"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/omarvaldez5/"
    - name: "telegram"
      url: "https://t.me/theDataFixer"
    - name: "rss"
      url: "https://thedatafixer.xyz/index.xml"
    - name: "email"
      url: "mailto:info@thedatafixer.xyz"
    
  
  assets:
    favicon: "/favicon/favicon.ico"
    favicon16x16: "/favicon/favicon-16x16.png"
    favicon32x32: "/favicon/favicon-32x32.png"
    apple_touch_icon: "/favicon/apple-touch-icon.png"
    safari_pinned_tab: "/favicon/favicon-16x16.png"


  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  UseHugoToc: false
  showtoc: true
  tocopen: true
  hideSummary: false
  comments: true

menu:
  main:
    - name: Tags
      url: /tags/
      weight: 5 
    - name: Archive
      url: /archive/
      weight: 5
    - name: 🔍 
      url: /search/
      weight: 10 
