baseURL: "https://thedatafixer.xyz/"
languageCode: en-us
title: Omar Valdez | The Data Fixer
theme: PaperMod
paginate: 5

enableRobotsTXT: true
enableEmoji: true

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  title: The Data Fixer
  Description:
  author: Omar Valdez
  description: "#dataengineering #datainfra #mlops #datascience #bigdata #dataanalytics"
  keywords: [blog, portfolio, theDataFixer, papermod]
  defaultTheme: dark
  disableThemeToggle: true

  label:
    icon: "/favicon/favicon.ico"
    iconHeight: 30
    text: "~$ cd .."

  homeInfoParams:
    Title: "The Data Fixer"

  profileMode:
    enabled: false
    title: The Data Fixer
    subtitle: Desbloqueando el potencial de los datos
    imageURL: terrariaMaker.png
    imageWidth: 130
    imageHeight: 120
    imageTitle: https://demize.gg/TerrariaMaker/
    buttons:
      # - name: Who am I?
      # url: whoami
      # - name: Articles
      # url: posts

  socialIcons:
    - name: "github"
      url: "https://github.com/theDataFixer"
    - name: "youtube"
      url: "https://youtube.com/@theDataFixer"
    - name: "spotify"
      url: "https://podcasters.spotify.com/pod/show/ovaldez"
    - name: "telegram"
      url: "https://t.me/theDataFixer"
    # - name: "twitter"
    #   url: "https://twitter.com/theDataFixer"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/omarvaldez5/"
    - name: "rss"
      url: "https://thedatafixer.xyz/index.xml"
    - name: "email"
      url: "mailto:info@thedatafixer.xyz"

  assets:
    favicon: "/favicon/favicon.ico"
    favicon16x16: "/favicon/favicon-16x16.png"
    favicon32x32: "/favicon/favicon-32x32.png"
    apple_touch_icon: "/favicon/apple-touch-icon.png"
    safari_pinned_tab: "/favicon/favicon-16x16.png"

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  UseHugoToc: false
  showtoc: true
  tocopen: true
  hideSummary: false
  comments: true

  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true

menu:
  main:
    - name: ~$whoami
      url: /whoami/
      weight: 7
    - name: Usos
      url: /usos/
      weight: 5
    - name: Data For Dummies
      url: /datafordummies/
      weight: 6
